Don't suggest deprecated `Serializable` interface for a PSR-14 Event
php-fig/fig-standards pull request #1302
Opened 2023-06-04 06:28 UTC by chalasr

2023-06-04 07:19 UTC, samdark approved these changes

2023-06-05 13:22 UTC, Crell requested changes
This is a change in the spec itself, technically, so would not be allowed.  I don't think that's an issue, though, since it doesn't say implementers SHOULD use Serializable, just that they MAY do so, along with various other options.  The intent is simply to say "whatev."  Removing Serializable is not needed for that, just like no one should be using `__sleep()` or `__wakeup()` these days but we're not removing those.

This is a won't-fix from me.  (The docblock newline is fine to make its own PR, though.)

2023-06-05 13:43 UTC, chalasr commented
Alright, makes sense. Maybe better give no hint at all and just remove that sentence altogether instead?

2023-06-05 19:24 UTC, Crell commented
No, that's a substantive change to the spec.  Those aren't allowed, even if it might make sense casually.

2023-06-05 19:24 UTC, closed without merging